name       : kdelibs4support
version    : 5.42.0
release    : 10
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.42/portingAids/kdelibs4support-5.42.0.tar.xz : cb594dd2910640e8ff9c8b2a9d1d8488f72bbc94dd24da70ee6d193b157a312a
license    :
    - GPL-2.0
    - LGPL-2.1
component  : programming
optimize   : lto
summary    : Legacy support for kdelibs 4 compatibility
description: |
    This framework provides code and utilities to ease the transition from kdelibs 4 to KDE Frameworks 5. This includes CMake macros and C++ classes whose functionality has been replaced by code in CMake, Qt and other frameworks.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(NetworkManager)
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(sm)
    - extra-cmake-modules
    - kauth-devel
    - kbookmarks-devel
    - kcodecs-devel
    - kcompletion-devel
    - kconfig-devel
    - kconfigwidgets-devel
    - kcoreaddons-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kded-devel
    - kdesignerplugin-devel
    - kdoctools-devel
    - kemoticons-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - kio-devel
    - kitemviews-devel
    - kjobwidgets-devel
    - knotifications-devel
    - kparts-devel
    - kservice-devel
    - ktextwidgets-devel
    - kunitconversion-devel
    - kwidgetsaddons-devel
    - kwindowsystem-devel
    - kxmlgui-devel
    - perl-uri
    - solid-devel
    - sonnet-devel
rundeps    :
    - kemoticons
    - devel :
        - kauth-devel
        - karchive-devel
        - kconfigwidgets-devel
        - kcoreaddons-devel
        - kcrash-devel
        - kdbusaddons-devel
        - kdesignerplugin-devel
        - kdoctools-devel
        - kemoticons-devel
        - kguiaddons-devel
        - kiconthemes-devel
        - kitemmodels-devel
        - kinit-devel
        - knotifications-devel
        - kparts-devel
        - ktextwidgets-devel
        - kunitconversion-devel
        - kwindowsystem-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
