name       : kdelibs4support
version    : 5.66.0
release    : 36
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.66/portingAids/kdelibs4support-5.66.0.tar.xz : 314d0ddb95c024c3d36dd262fcaa9295b462e6430f84b22c82f145029e3b2708
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming
optimize   : lto
summary    : Legacy support for kdelibs 4 compatibility
description: |
    This framework provides code and utilities to ease the transition from kdelibs 4 to KDE Frameworks 5. This includes CMake macros and C++ classes whose functionality has been replaced by code in CMake, Qt and other frameworks.
builddeps  :
    - pkgconfig(Qt5Designer)
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libnm)
    - pkgconfig(sm)
    - extra-cmake-modules
    - kauth-devel
    - kcodecs-devel
    - kconfigwidgets-devel
    - kcrash-devel
    - kdbusaddons-devel
    - kded-devel
    - kdesignerplugin-devel
    - kdoctools-devel
    - kemoticons-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - ki18n-devel
    - kiconthemes-devel
    - knotifications-devel
    - kparts-devel
    - kunitconversion-devel
    - kwindowsystem-devel
    - perl-uri
rundeps    :
    - kdesignerplugin
    - kemoticons
    - devel :
        - kauth-devel
        - karchive-devel
        - kconfigwidgets-devel
        - kcoreaddons-devel
        - kcrash-devel
        - kdbusaddons-devel
        - kdesignerplugin-devel
        - kdoctools-devel
        - kemoticons-devel
        - kguiaddons-devel
        - kiconthemes-devel
        - kitemmodels-devel
        - kinit-devel
        - knotifications-devel
        - kparts-devel
        - ktextwidgets-devel
        - kunitconversion-devel
        - kwindowsystem-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
