name       : kdelibs4support
version    : 5.81.0
release    : 52
source     :
    - https://cdn.download.kde.org/stable/frameworks/5.81/portingAids/kdelibs4support-5.81.0.tar.xz : 6614d9d8c004e15359ef0f5ac37419d706beb0bcc53fafecc3536a340d8963b2
homepage   : https://community.kde.org/Frameworks
license    :
    - GPL-2.0-or-later
    - LGPL-2.1-or-later
component  : programming.library
summary    : Legacy support for kdelibs 4 compatibility
description: |
    This framework provides code and utilities to ease the transition from kdelibs 4 to KDE Frameworks 5. This includes CMake macros and C++ classes whose functionality has been replaced by code in CMake, Qt and other frameworks.
optimize   : lto
builddeps  :
    - pkgconfig(Qt5Svg)
    - pkgconfig(Qt5X11Extras)
    - pkgconfig(libnm)
    - pkgconfig(sm)
    - pkgconfig(x11)
    - kcrash-devel
    - kdbusaddons-devel
    - kded-devel
    - kdesignerplugin-devel
    - kdoctools-devel
    - kemoticons-devel
    - kglobalaccel-devel
    - kguiaddons-devel
    - kiconthemes-devel
    - knotifications-devel
    - kparts-devel
    - kunitconversion-devel
    - perl-uri
rundeps    :
    - kdesignerplugin
    - kemoticons
    - devel :
        - karchive-devel
        - kcrash-devel
        - kdbusaddons-devel
        - kdesignerplugin-devel
        - kdoctools-devel
        - kemoticons-devel
        - kguiaddons-devel
        - kiconthemes-devel
        - kinit-devel
        - kio-devel
        - kitemmodels-devel
        - knotifications-devel
        - kparts-devel
        - ktextwidgets-devel
        - kunitconversion-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |-
    %ninja_install
    rm -rf $installdir/usr/share/doc
